
name: Datree

on:
  push:
    branches: [ "main" ]

# for pull request from other branches in the repo. Cons - Doesn't work where Github tokens are required
#   pull_request:
#     # The branches below must be a subset of the branches above
#     branches: [ "main" ]

# for pull request from forked repo. Cons - runs only in the pull request's target branch, and not the pull request's branch itself (which wouldn't include the latest commit in the PR).
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches: [ "main" ]    


permissions:
  contents: read

jobs:
  datree:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test *.yaml with Datree 
      # pass on failure so that code report upload can succeed 
        # continue-on-error: true     
        uses: datreeio/action-datree@de67ae7a5133d719dc794e1b75682cd4c5f94d8a
        env:
          # In order to use the Datree action you will need to have a Datree token.
          # See https://hub.datree.io/setup/account-token#1-get-your-account-token-from-the-dashboard to acquire your token.
          DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
        with:
          # Add the path to the configuration file/s that you would like to test.
          # See https://github.com/datreeio/action-datree#usage for all available options.
          path: 'kubernetes/*.yaml'
          # Setting a SARIF output will generate a file named "datree.sarif" containing your test results
          cliArguments: "-o sarif --only-k8s-files"

      - name: Test *.yml with Datree 
      # pass on failure so that code report upload can succeed 
        # continue-on-error: true     
        uses: datreeio/action-datree@de67ae7a5133d719dc794e1b75682cd4c5f94d8a
        env:
          # In order to use the Datree action you will need to have a Datree token.
          # See https://hub.datree.io/setup/account-token#1-get-your-account-token-from-the-dashboard to acquire your token.
          DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
        if: success() || failure()            
        with:
          # Add the path to the configuration file/s that you would like to test.
          # See https://github.com/datreeio/action-datree#usage for all available options.
          path: 'kubernetes/*.yml'
          # Setting a SARIF output will generate a file named "datree.sarif" containing your test results
          cliArguments: "-o sarif --only-k8s-files"

      - name: Upload result to GitHub Code Scanning to be displayed as security alerts 
        uses: github/codeql-action/upload-sarif@v2

        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()        
        with:
          sarif_file: datree.sarif
          wait-for-processing: true
